version: 2

builds:
  - main: .
    binary: mermaid-preview-cli
    ldflags:
      - -s -w -X github.com/mxcoppell/mermaid-preview-cli/internal/version.Version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - repository:
      owner: mxcoppell
      name: homebrew-tap
    name: mermaid-preview-cli
    homepage: https://github.com/mxcoppell/mermaid-preview-cli
    description: CLI tool for previewing Mermaid diagrams
    license: MIT
    install: |
      bin.install "mermaid-preview-cli"

